(function(){
function moneyNumber(v){if(!v)return null;const n=Number(String(v).replace(/[^0-9.,-]/g,'').replace(/,(?=\d{3}\b)/g,'').replace(',','.'));return Number.isFinite(n)?n:null}
function normalizeText(text){return String(text||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').trim()}
function findCurrency(text){const upper=text.toUpperCase();const patterns=[['AED',/\bAED\b|\bDHS?\b|د\.إ/i],['USD',/\bUSD\b|US\s*\$|\$/i],['EUR',/\bEUR\b|€/i],['GBP',/\bGBP\b|£/i],['SAR',/\bSAR\b|\bSR\b/i],['QAR',/\bQAR\b/i],['OMR',/\bOMR\b/i],['INR',/\bINR\b|₹/i]];for(const [code,re] of patterns)if(re.test(upper))return{value:code,confidence:.9};return{value:'AED',confidence:.35}}
function parseDate(text){const candidates=[/(?:invoice\s*date|date|receipt\s*date)\s*[:#-]?\s*(\d{4}[\/-]\d{1,2}[\/-]\d{1,2})/i,/(?:invoice\s*date|date|receipt\s*date)\s*[:#-]?\s*(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})/i,/\b(\d{4}[\/-]\d{1,2}[\/-]\d{1,2})\b/,/\b(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4})\b/,/\b(\d{1,2}\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+\d{2,4})\b/i];for(let i=0;i<candidates.length;i++){const m=text.match(candidates[i]);if(!m)continue;const raw=m[1];let y,mo,d;if(/^\d{4}/.test(raw)){[y,mo,d]=raw.split(/[\/-]/).map(Number)}else if(/^[0-9]{1,2}\s+[A-Za-z]/.test(raw)){const dt=new Date(raw);if(!Number.isNaN(dt.valueOf()))return{value:dt.toISOString().slice(0,10),confidence:i<2?.95:.8};continue}else{const parts=raw.split(/[\/-]/).map(Number);d=parts[0];mo=parts[1];y=parts[2]<100?2000+parts[2]:parts[2]}if(y>=2000&&y<=2100&&mo>=1&&mo<=12&&d>=1&&d<=31)return{value:`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`,confidence:i<2?.95:.75}}return{value:null,confidence:0}}
function findBillNo(text){for(const re of [/(?:invoice|receipt|bill|tax invoice)\s*(?:no\.?|number|#)\s*[:#-]?\s*([A-Z0-9][A-Z0-9\/-]{2,})/i,/(?:inv\.?\s*no\.?)\s*[:#-]?\s*([A-Z0-9][A-Z0-9\/-]{2,})/i]){const m=text.match(re);if(m)return{value:m[1].trim(),confidence:.92}}return{value:null,confidence:0}}
function findJobNo(text){const m=text.match(/(?:enq(?:uiry)?|job|project|work\s*order|wo)\s*(?:no\.?|number|#)?\s*[:#-]?\s*([A-Z0-9][A-Z0-9\/-]{2,})/i);return m?{value:m[1].trim(),confidence:.82}:{value:null,confidence:0}}
function extractAmounts(text){const lines=text.split('\n').map(s=>s.trim()).filter(Boolean),scored=[];const amountRe=/(?:AED|DHS?|USD|EUR|GBP|SAR|QAR|OMR|INR|[$€£₹])?\s*([0-9][0-9,]*(?:\.\d{1,3})?)/ig;for(const line of lines){const lower=line.toLowerCase();let score=0;if(/grand\s*total|total\s*due|amount\s*due|net\s*total|total\s*amount/.test(lower))score=100;else if(/\btotal\b/.test(lower)&&!/sub\s*total|subtotal/.test(lower))score=80;else if(/sub\s*total|subtotal/.test(lower))score=45;if(!score)continue;const vals=[...line.matchAll(amountRe)].map(m=>moneyNumber(m[1])).filter(Number.isFinite);if(vals.length)scored.push({value:vals[vals.length-1],score,line})}scored.sort((a,b)=>b.score-a.score||b.value-a.value);let total=scored[0]?.value??null,totalConfidence=scored[0]?(scored[0].score>=100?.96:.86):0;if(total==null){const vals=[...text.matchAll(/(?:AED|DHS?|USD|EUR|GBP|SAR|QAR|OMR|INR|[$€£₹])\s*([0-9][0-9,]*(?:\.\d{1,3})?)/ig)].map(m=>moneyNumber(m[1])).filter(v=>Number.isFinite(v)&&v>0&&v<1e8);if(vals.length){total=Math.max(...vals);totalConfidence=.45}}let vat=null,vatConfidence=0;for(const line of lines){if(!/\b(vat|tax)\b/i.test(line))continue;const vals=[...line.matchAll(amountRe)].map(m=>moneyNumber(m[1])).filter(Number.isFinite);if(vals.length){vat=vals[vals.length-1];vatConfidence=.82;break}}return{total,totalConfidence,vat,vatConfidence}}
function findVendor(text){const lines=text.split('\n').map(s=>s.trim()).filter(Boolean),skip=/invoice|receipt|tax invoice|date|phone|tel|email|www\.|trn|vat|customer|bill to|address|cashier|page \d/i;for(const line of lines.slice(0,12)){const cleaned=line.replace(/[^\p{L}\p{N}&.' -]/gu,'').trim();if(cleaned.length<3||cleaned.length>80||skip.test(cleaned))continue;const letters=(cleaned.match(/\p{L}/gu)||[]).length;if(letters>=3)return{value:cleaned,confidence:.68}}return{value:null,confidence:0}}
function findDescription(text,vendor){const explicit=text.match(/(?:description|details|particulars|service|item)\s*[:#-]\s*([^\n]{3,140})/i);if(explicit){const value=explicit[1].replace(/\s{2,}/g,' ').trim();if(value&&!/^(qty|quantity|price|amount|rate|total)$/i.test(value))return{value,confidence:.82}}const skip=/tax invoice|invoice|receipt|date|bill\s*to|ship\s*to|customer|phone|tel|email|www\.|trn|vat|subtotal|total|amount|cashier|payment|address|po\s*(?:no|number)|job\s*(?:no|number)|enq(?:uiry)?|terms|thank you/i;for(const raw of text.split('\n').map(x=>x.trim()).filter(Boolean).slice(2,28)){if(vendor&&raw.toLowerCase()===vendor.toLowerCase()||skip.test(raw)||raw.length<4||raw.length>120)continue;const letters=(raw.match(/\p{L}/gu)||[]).length,digits=(raw.match(/\d/g)||[]).length;if(letters>=4&&digits<raw.length*.45)return{value:raw,confidence:.55}}return{value:vendor?`Expense - ${vendor}`:'',confidence:vendor?.35:0}}
function parseInvoiceText(raw){const text=normalizeText(raw),date=parseDate(text),vendor=findVendor(text),billNo=findBillNo(text),jobNo=findJobNo(text),currency=findCurrency(text),amounts=extractAmounts(text),description=findDescription(text,vendor.value);return{date:date.value,vendor:vendor.value,bill_no:billNo.value,enq_job_no:jobNo.value,currency:currency.value,total:amounts.total,vat:amounts.vat,description:description.value,confidence:{date:date.confidence,vendor:vendor.confidence,bill_no:billNo.confidence,enq_job_no:jobNo.confidence,currency:currency.confidence,amount:amounts.totalConfidence,vat:amounts.vatConfidence,description:description.confidence}}}
window.SMSParser={parseInvoiceText};
})();